# ServiceAccount for ibmcloud-object-storage-plugin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibmcloud-object-storage-plugin
  namespace: kube-system
imagePullSecrets:
  - name: bluemix-default-secret
  - name: bluemix-default-secret-regional
  - name: bluemix-default-secret-international
---
#ClusterRole with minimum permissions required for ibmcloud-object-storage-plugin
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ibmcloud-object-storage-plugin
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["cluster-info"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["icos-secret"]
  verbs: ["get"]
---
#ClusterRole for giving read secrets permission to ibmcloud-object-storage-plugin
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ibmcloud-object-storage-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  #resourceNames: [""]
  verbs: ["get"]
---
#ClusterRoleBinding for binding ClusterRole "ibmcloud-object-storage-plugin"
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ibmcloud-object-storage-plugin
subjects:
- kind: ServiceAccount
  name: ibmcloud-object-storage-plugin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ibmcloud-object-storage-plugin
  apiGroup: rbac.authorization.k8s.io
---
#ClusterRoleBinding for binding ClusterRole "ibmcloud-object-storage-secret-reader"
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ibmcloud-object-storage-secret-reader
subjects:
- kind: ServiceAccount
  name: ibmcloud-object-storage-plugin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ibmcloud-object-storage-secret-reader
  apiGroup: rbac.authorization.k8s.io
