apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sftp-deployment
  labels:
    app: sftp-deployment
spec:
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
      - image: registry.eu-gb.bluemix.net/sftp-service/fauria/vsftpd
        name: sftp-container
        ports:
        - containerPort: 21
          protocol: TCP
          name: "ftp-server"
        env:
        - name: FTP_USER
          value: "user"
        - name: FTP_PASS
          value: "pass1234"
        volumeMounts:
        - name: task-pv-storage
          mountPath: "/home/vsftpd"
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: s3fs-test-pvc
        

