apiVersion: v1
kind: Secret
type: ibm/ibmc-s3fs
metadata:
  name: icos-secret
data:
  access-key: OTE1YzQ1YzY2N2ZmNGU2ZmEzZjA1OWRhMjdkMTVjMzg=
  secret-key: Y2I5ZjA1ZDhlYjgxMGNmNGM2NmFmOTIzMGJiMzU4ZmIxYjJiZjY4YTZiNWNmN2Qx
  api-key: QkVETXp6TTBJRTV5NDJJbmhUSndQYkMwTXdweEg1NkRWOXlOMHM1UXkzQms=
  service-instance-id: M2JmMGQ2NGYtMzk5Mi00NTJiLThiMTAtMWNiYTdkMmFjMDE2